config/routes.rb
Rails.application.routes.draw do
  get 'conversations/:index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :advertisements
  resources :conversations, only: [:index]
  
  devise_for :users
  get 'static_pages/home'
  get 'static_pages/help'

   root 'static_pages#home'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
       user ||= User.new # guest user (not logged in)
       if user.admin?
         can :manage, :advertisements
       else
         can :read, :all
         if user.custom?
           can :create, Advertisement
           can :update, Advertisement do |advertisement|
             Advertisement.try(:user) == user
           end
         end
       end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/advertisement.rb
# == Schema Information
#
# Table name: advertisements
#
#  id          :integer          not null, primary key
#  user_id     :integer
#  city_id     :integer
#  district_id :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Advertisement < ActiveRecord::Base
  belongs_to :user
  belongs_to :city
  belongs_to :district
end

app/models/city.rb
# == Schema Information
#
# Table name: cities
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class City < ActiveRecord::Base
end

app/models/district.rb
# == Schema Information
#
# Table name: districts
#
#  id         :integer          not null, primary key
#  name       :string
#  city_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class District < ActiveRecord::Base
  belongs_to :city
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default("0"), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  first_name             :string
#  last_name              :string
#  login                  :string
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  acts_as_messageable     
  before_create :default_status
         
  enum status: [:admin, :custom]
  
  private 
  def default_status
    self.status = User.statuses[:custom]
  end
end

app/controllers/advertisements_controller.rb
class AdvertisementsController < ApplicationController
  load_and_authorize_resource
  
  before_action :set_advertisement, only: [:show, :edit, :update, :destroy]

  # GET /advertisements
  # GET /advertisements.json
  def index
    @advertisements = Advertisement.all
  end

  # GET /advertisements/1
  # GET /advertisements/1.json
  def show
  end

  # GET /advertisements/new
  def new
    @advertisement = Advertisement.new
  end

  # GET /advertisements/1/edit
  def edit
  end

  # POST /advertisements
  # POST /advertisements.json
  def create
    @advertisement = Advertisement.new(advertisement_params)
    @advertisement.user = current_user
    respond_to do |format|
      if @advertisement.save
        format.html { redirect_to @advertisement, notice: 'Advertisement was successfully created.' }
        format.json { render :show, status: :created, location: @advertisement }
      else
        format.html { render :new }
        format.json { render json: @advertisement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /advertisements/1
  # PATCH/PUT /advertisements/1.json
  def update
    respond_to do |format|
      if @advertisement.update(advertisement_params)
        format.html { redirect_to @advertisement, notice: 'Advertisement was successfully updated.' }
        format.json { render :show, status: :ok, location: @advertisement }
      else
        format.html { render :edit }
        format.json { render json: @advertisement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /advertisements/1
  # DELETE /advertisements/1.json
  def destroy
    @advertisement.destroy
    respond_to do |format|
      format.html { redirect_to advertisements_url, notice: 'Advertisement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_advertisement
      @advertisement = Advertisement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def advertisement_params
      params.require(:advertisement).permit(:user_id, :city_id, :district_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from CanCan::AccessDenied do |exception|
    flash[:error] = "Access denied."
    redirect_to(:back)
  end  
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!
  before_action :get_mailbox

  def index
    @conversations = @mailbox.inbox.paginate(page: params[:page], per_page: 10)
  end
  private
  def get_mailbox
    @mailbox ||= current_user.mailbox
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    redirect_to advertisements_path if user_signed_in?
  end
    

  def help
  end
end

app/helpers/advertisements_helper.rb
module AdvertisementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/advertisements/_form.html.haml
= simple_form_for @advertisement do |f|
  = f.input :city, collection: City.all.order(:name)
  = f.input :district, collection: District.all
  = f.submit 'Save'

app/views/advertisements/edit.html.haml
%h1 Editing advertisement

= render 'form'

= link_to 'Show', @advertisement
\|
= link_to 'Back', advertisements_path

app/views/advertisements/index.html.haml
%h1 Listing advertisements

%table
  %thead
    %tr
      %th User
      %th City
      %th District
      %th
      %th
      %th

  %tbody
    - @advertisements.each do |advertisement|
      %tr
        %td= advertisement.user
        %td= advertisement.city
        %td= advertisement.district
        %td= link_to 'Show', advertisement
        %td= link_to 'Edit', edit_advertisement_path(advertisement)
        %td= link_to 'Destroy', advertisement, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Advertisement', new_advertisement_path

app/views/advertisements/new.html.haml
%h1 Nowe ogłoszenie

= render 'form'

= link_to 'Back', advertisements_path

app/views/advertisements/show.html.haml
%p#notice= notice

%p
  %b User:
  = @advertisement.user
%p
  %b City:
  = @advertisement.city
%p
  %b District:
  = @advertisement.district

= link_to 'Edit', edit_advertisement_path(@advertisement)
\|
= link_to 'Back', advertisements_path

app/views/conversations/_conversation.html.haml
%li.list-group-item clearfix
  = link_to conversation.subject, conversation_path(conversation)

app/views/conversations/index.html.haml
.page_header "Your Conversations"
%ul.list-group
  = render partial: 'conversations/conversation', collection: @conversations 
= will_paginate

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Zurb Foundation
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert-box round #{name.to_s == 'notice' ? 'success' : 'alert'}", "data-alert" => ""}
      = content_tag :div, msg
      %a.close{:href => "#"} &times;

app/views/layouts/_navigation.html.erb
     <nav class="top-bar" data-topbar>
        <ul class="title-area">
           
          <li class="name">
            <h1>
              <%= link_to 'Share room', root_path%>
              
            </h1>
          </li>
          <li class="toggle-topbar menu-icon"><a href="#"><span>menu</span></a></li>
        </ul>
     
     	
        <section class="top-bar-section">
        <% if !user_signed_in? %>
          <ul class="right">
            <li class="divider"></li>
            <li class="divider"></li>
            <li>
       			<%= link_to new_user_session_path do%>
       				<%= image_tag 'arrow.ico'%> Logowanie	
  				<%end%>
           	</li>
            <li class="divider"></li>
            <li>
            	<%= link_to new_user_registration_path do%>
       				<%= image_tag 'add-user.ico'%> Rejesracja	
  				<%end%>
            </li>
          </ul>
        <%else%>
          <ul class="right">
            <li>
       			<%= link_to edit_user_registration_path do%>
       			 <%= current_user.email%>	
  				<%end%>
           	</li>
            <li class="divider"></li>
            <li>
            	<%= link_to  destroy_user_session_path, method: :delete  do%>
       				wyloguj	
  				<%end%>
            </li>
            <li><%= link_to 'Your Conversations', conversations_path %></li>
          </ul>
        <%end%>
        </section>
        
       
      </nav>

     

app/views/layouts/_navigation_links.html.haml
%a.item
  =image_tag 'home.svg',class: "svg", style: 'fill: white;'
  %label Home  
%a.item
  =image_tag 'home.svg'
  %label Logowanie
%a.item
  =image_tag 'home.svg'
  %label Rejestracja   

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Share Room'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Share Room'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    -# Modernizr is required for Zurb Foundation
    = javascript_include_tag 'vendor/modernizr'
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main.with-padding{:role => "main"}
      = render 'layouts/messages'
      = yield

app/views/layouts/test.html.erb
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1><a href="#">My Site</a></h1>
    </li>
     <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <li class="active"><a href="#">Right Button Active</a></li>
      <li class="has-dropdown">
        <a href="#">Right Button Dropdown</a>
        <ul class="dropdown">
          <li><a href="#">First link in dropdown</a></li>
          <li class="active"><a href="#">Active link in dropdown</a></li>
        </ul>
      </li>
    </ul>

    <!-- Left Nav Section -->
    <ul class="left">
      <li><a href="#">Left Nav Button</a></li>
    </ul>
  </section>
</nav>

app/views/layouts/test.html.haml
%nav.top-bar{"data-topbar" => "", :role => "navigation"}
  %ul.title-area
    %li.name
      %h1
        %a{:href => "#"} My Site
    / Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone
    %li.toggle-topbar.menu-icon
      %a{:href => "#"}
        %span Menu
  %section.top-bar-section
    / Right Nav Section
    %ul.right
      %li.active
        %a{:href => "#"} Right Button Active
      %li.has-dropdown
        %a{:href => "#"} Right Button Dropdown
        %ul.dropdown
          %li
            %a{:href => "#"} First link in dropdown
          %li.active
            %a{:href => "#"} Active link in dropdown
    / Left Nav Section
    %ul.left
      %li
        %a{:href => "#"} Left Nav Button

app/views/static_pages/help.html.haml
%h1 StaticPages#help
%p Find me in app/views/static_pages/help.html.haml

app/views/static_pages/home.html.haml
.row.home
  .large-12.large-offset-0.small-12.columns.box-with-shadow.border-radius.with-padding
    %h1.center Share Room
    .row.info
      .large-6.columns.center
        %p.border-radius.box-with-shadow-min Szukanie mieszkania nigdy nie było tak proste
      .large-6.columns.center
        %p.border-radius.box-with-shadow-min Wynajmowanie nigdy nie było tak szybkie